version: '3'

services:
  asterisk:
    container_name: asterisk
    image: sss666/asterisk
    restart:  always
    ports:
      - "5060:5060/udp"
    hostname: asterisk
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # volumes:
    #   -
    # command: bash -c 'while true; do sleep 20180101; done'

